"""add image_url to services

Revision ID: f18cb8181ad6
Revises: 340aa0261a5c
Create Date: 2025-12-29 14:12:10.330839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18cb8181ad6'
down_revision: Union[str, Sequence[str], None] = '340aa0261a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image_url')
    # ### end Alembic commands ###
